services:
  postgresql:
    container_name: ms_pg_sql
    image: postgres:16.3
    environment:
      POSTGRES_USER: qwe
      POSTGRES_PASSWORD: qwe
      PGDATA: /var/lib/data/postgres
    volumes:
      - postgres:/var/lib/data/postgres
    ports:
      - "3333:5432"
    networks:
      - microservices-net
    restart: unless-stopped

  redis:
    container_name: ms_redis
    image: redis
    environment:
      REDIS_PASSWORD: qwe
    command: ["redis-server", "--requirepass", "qwe"]
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    networks:
      - microservices-net
    restart: unless-stopped

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
  redis: